### ISSUE TITLE
Ok mister microcontrollers i found a few mods

### ISSUE THREAD

**Issue by karmette** [MicrocontrollersDev/LabyMod-Alternatives#3]
HD Skins- [CustomSkinLoader](https://www.curseforge.com/minecraft/mc-mods/customskinloader) found this mod that allows HD Skins that supports 1.8, 1.8.8, and 1.8.9

[more player models](https://www.curseforge.com/minecraft/mc-mods/more-player-models)
Client side mod that lets you, uh, use custom player models, as well as 3d hat layers... you should test this I'm too lazy to do it myself

ok enjoy micro controler

**Comment by MicrocontrollersDev** [comment]
thanks you kar mette. added both (with warning for more player models as i have looked at it at the past but thought it was needed server side. i am also way too lazy to test soooo)

**Comment by MicrocontrollersDev** [comment]
ended up removing more player models. i dont feel comfortable having that entire mod just for the minecraft head to be more 3D
